require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Review = require('../models/Review');

// Testimonials gathered from https://www.launchpadenglish.com/what-our-students-say/
// General institute testimonials (not tied to one specific course), so
// courseSlug is 'general' - they show in the site-wide review feed
// (ReviewList with no courseSlug) but not under any single course page.
// Photos are hotlinked to the original launchpadenglish.com URLs.
const TESTIMONIALS = [
  { name: 'Dr. Meenu Bhatia', title: 'Surgeon (AIIMS)', text: "I joined Launch Pad English to improve my English skills, and it has been a great experience. The teachers are very helpful and explain everything clearly. The classes are easy to follow, and I feel more confident in speaking and writing English now. Good communication is important, and Launch Pad English has really helped me. I highly recommend it to anyone looking to improve their English skills.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-18-at-12.58.04-PM.jpeg' },
  { name: 'Aditya', title: 'Student', text: "I joined Launch Pad English to improve my English skills, and it has been a great experience. The teachers are very helpful and explain everything clearly. The classes are easy to follow, and I feel more confident in speaking and writing English now.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-17-at-4.25.28-PM.png' },
  { name: 'Aman Shahi', title: 'B.Tech', text: "I joined Launch Pad English to improve my English skills, and it has been a great experience. The teachers are very helpful and explain everything clearly. The classes are easy to follow, and I feel more confident in speaking and writing English now.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-17-at-4.25.28-PM-2.png' },
  { name: 'Arshad Khan', title: 'B.Sc', text: "I joined Launch Pad English to improve my English skills, and it has been a great experience. The teachers are very helpful and explain everything clearly. The classes are easy to follow, and I feel more confident in speaking and writing English now.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-17-at-4.25.28-PM-1-768x946.jpeg' },
  { name: 'Komal', title: 'Nursing Officer In AIIMS', text: "I joined Launch Pad English to improve my English skills, and it has been a great experience. The teachers are very helpful and explain everything clearly. As a Nursing Officer at AIIMS, good communication is important, and Launch Pad English has really helped me.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/3481c5d2-8ff8-46b7-98de-ffec66dfedca-e1728375753742.jpeg' },
  { name: 'Ankit', title: 'BPSC Account Officer', text: "I had an excellent experience at Launch Pad English! The coaching provided was top-notch, helping me prepare effectively for the BPSC Account Officer exam. The supportive environment and dedicated instructors made a significant difference in my learning. Thank you, Launch Pad English, for your invaluable guidance!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-14-at-12.23.58-PM-e1728373645546.png' },
  { name: 'Madhumalini', title: 'Sub Inspector', text: "A heartfelt thank you to Launch Pad English! The course helped me refine my English, making it easier to collaborate internationally. I appreciate the guidance and support from the team!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/file-e1728374372363.jpg' },
  { name: 'Sanjay', title: 'International Chef', text: "I Have completed Spoken English course here at Launch Pad English Institute. I am extremely, extremely satisfied with the whole experience at Launch Pad. The atmosphere is very warm and friendly, and it seems your teachers really care about the improvement of their students. Well, actually, lesson plans are very personal, so every student finds his or her own package. I can already see an obvious change in both my vocabulary and my ability to talk.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/sanjay-internationl-chef-1-e1728374395243-768x641.jpg' },
  { name: 'Shushanta Lenka', title: 'Defence Army', text: "Thank you, Launch Pad English! Your classes have made learning enjoyable and effective. I've gained so much confidence in my English skills, which is vital for my career in the army. I appreciate all the hard work!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-13-at-4.20.46-PM-e1728375409792.png' },
  { name: 'Mukesh', title: 'Delhi Police', text: "Thank you, Launch Pad English! The practical lessons and supportive teachers helped me improve my English skills immensely. I feel better prepared for my role in the Delhi Police. Your dedication to students is truly appreciated!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/mukesh.jpg' },
  { name: 'Chandra Bhushan', title: 'DU Professor', text: "Grateful to Launch Pad English! The course has sharpened my communication skills, making lectures more engaging. The faculty's dedication is truly inspiring. I feel more confident in my English proficiency!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/322379993_840854350477493_3423455714437760064_n-e1728375623157.jpg' },
  { name: 'Priya', title: 'Medical transcriptionist H.O.D', text: "Thank you, Launch Pad English, for transforming my communication skills! Your engaging lessons and practical approach made a significant difference in my professional life. I now feel more confident in my role as a Medical Transcriptionist!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/06/priya-mittle.png' },
  { name: 'Dr. Chandan', title: 'Doctor in GTB Hospital', text: "I'm truly grateful to Launch Pad English for their exceptional teaching methods. The small class sizes and personalized attention helped me improve my English significantly. I can now connect better with my patients!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/20240308_181728-300x300-1.png' },
  { name: 'Rajat', title: 'Nursing Officer in AIIMS', text: "Joining Launch Pad English was a game changer for me! The supportive instructors and engaging lessons made learning enjoyable. I gained confidence in my communication skills, which has been invaluable in my nursing career. Thank you, Launch Pad, for your dedication to helping students succeed!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/20240308_181313-300x300-1.png' },
  { name: 'Anjali Gupta', title: 'Nursing Officer in Safdarjung', text: "I'm truly grateful to Launch Pad English! The friendly atmosphere and practical lessons transformed my English skills. Now, I can communicate effectively with patients and colleagues. A heartfelt thank you to the amazing team for their encouragement and guidance throughout my learning journey!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/snapedit_1715410072426.png' },
  { name: 'Ajay', title: 'Technical Staff in AIIMS', text: "Thanks to Launch Pad English, my communication skills have improved significantly! The instructors provided personalized attention and valuable resources, helping me excel in my professional role. I'm grateful for the supportive environment that made learning enjoyable. Highly recommend it to anyone looking to enhance their English skills!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/03/20240308_181401-1024x1024.jpg' },
  { name: 'Vipin Kumar', title: 'C.A.', text: "I'm truly grateful for Launch Pad English! The coaching has been invaluable in enhancing my communication skills, which are crucial in my profession. The supportive environment and expert guidance made learning enjoyable and effective. I feel more confident in my English proficiency, which has positively impacted my career. Thank you, Launch Pad English!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/5b24f52a-7227-49f5-81fa-62052affa66d-300x300-1.webp' },
  { name: 'Tarun Kumar', title: 'Railway', text: "I owe my improved English skills to Launch Pad English! The trainers were supportive and patient, making learning enjoyable. Thanks to them, I communicate better in my Railway job and feel more confident. Highly recommend to anyone eager to learn!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/40b06ecb-495b-4c4b-875e-06709ea22992-300x300-1.webp' },
  { name: 'Divijyoti', title: 'Nursing Staff (Fortis H.)', text: "I extend my heartfelt gratitude to Launch Pad English for their outstanding English coaching. The curriculum was meticulously designed, and the instructors were highly knowledgeable. This experience has significantly enhanced my professional communication skills. Thank you for your commitment to excellence.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Divyajyoti-Nursing-Staff.webp' },
  { name: 'Kunal Singh', title: 'Teacher', text: "So grateful for Launch Pad English! This platform has made a huge difference in my understanding of literature. Thank you for helping me excel!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/c5b6eec3-a459-42cd-a230-6969a00dfe86-e1728458559498.webp' },
  { name: 'Armeet', title: 'Nursing Staff (AIIMS)', text: "Just wanted to extend my sincerest thanks to the team at Launch Pad English. The resources and guidance have been invaluable. You're the best!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Armeet-nursing-staff.webp' },
  { name: 'Seema', title: 'Nursing Staff (AIIMS)', text: "I can't express how thankful I am for Launch Pad English. It's been a game-changer for my English speaking, listening and writing skills. Thanks a lot!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Seema-Nursing-Staff.webp' },
  { name: 'Amanpreet', title: 'Physio Therapist', text: "I am so appreciative of Launch Pad English! It has made studying English enjoyable and effective. Many thanks for the wonderful content.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Amanpreet-Physio-therapist.webp' },
  { name: 'Neha Naz', title: 'Professor (DU)', text: "Absolutely thrilled with my experience at Launch Pad English Learning Institute! The faculty's dedication to each student's progress is commendable, and the interactive lessons have truly helped me improve my language skills. Highly recommended!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Neha-Naz-Professor-DU.webp' },
  { name: 'Sanjay Shah', title: 'Professor (DU)', text: "Attending Launch Pad English Learning Institute has been a game-changer for me. The experienced instructors go above and beyond in ensuring that every student grasps the concepts thoroughly. I'm already seeing a noticeable improvement in my language fluency!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/sanjay-bharatia-1024x976.jpg' },
  { name: 'Rakesh', title: 'Professor', text: "If you're looking to enhance your English language skills, look no further than Launch Pad English Learning Institute. The innovative teaching methods, regular assessments, and constructive feedback make learning a joyous experience.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Rakesh-professor.webp' },
  { name: 'Vinod Kumar', title: 'Delhi Police', text: "I had heard great things about Launch Pad English Learning Institute, and I must say, they exceeded all my expectations. The well-structured courses and supportive staff make learning English not only effective but also enjoyable. Definitely a top-notch institute!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/vinod-kumar-1.webp' },
  { name: 'Rajkishor', title: 'Professor (BHU)', text: "I'm so grateful to have found Launch Pad English Learning Institute. The approachable teachers, well-equipped facilities, and practical learning resources have tremendously helped me in honing my English proficiency. A big thumbs up from a satisfied student!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/3-R.K.Arya-Professor-BHU-300x300-1.webp' },
  { name: 'Manoj Singh', title: 'C.T.O BPSC', text: "Launch Pad English Learning Institute has truly transformed the way I perceive language learning. Their focus on individual progress, interactive sessions, and industry-oriented curriculum sets them apart from the rest. I can't recommend them highly enough!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Manoj-Singh-CTO-launchpadenglish-student-e1728459617504.webp' },
  { name: 'Kamakhya Pandey', title: 'Banker', text: "Launch Pad English Learning Institute's dedication to creating a supportive learning environment is truly admirable. The encouragement from the faculty, combined with the engaging lessons, has made my English learning journey a memorable and rewarding experience. Highly recommended!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2022/01/Kamakhya-Pandey-Banker-300x300.jpg' },
  { name: 'Mamta Sharma', title: 'Advocate', text: "Launch Pad English Learning Institute is responsible for the remarkable progress I've made in my language skills since enrolling. The instructors' expertise, the innovative teaching techniques, and the emphasis on practical application have truly set me up for success. A top choice for English learning!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/3db76fca-f89d-4846-922b-bab28ff8a1a2-150x150-1-e1728388600716.webp' },
  { name: 'Sourav Jha', title: 'SBI P.O', text: "If you're looking for a place to enhance your English language abilities, look no further than Launch Pad English Learning Institute. The emphasis on personalized attention, interactive learning, and continuous feedback make this institute stand out from the rest.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Sourav-Jha-_SBI-PO_.webp' },
  { name: 'Renu Gupta', title: 'Sub Inspector', text: "Choosing Launch Pad English for my Competitive Exams preparation was one of the best decisions I made. The comprehensive curriculum and focused lessons helped me enhance my vocabulary and grammar. I appreciate the interactive sessions that encouraged active participation, making learning enjoyable. A big thank you to the entire team for their commitment to our success!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Renu-Gupta-Sup-Inspector-e1728462556941.webp' },
  { name: 'Anand Kumar', title: 'Peshkar', text: "I came to Launch Pad English Learning Institute with a goal to improve my English proficiency, and I can confidently say that this institute has helped me exceed that goal. The tailored approach, the encouraging environment, and the practical exercises have all contributed to my progress.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Anand-kumar-Peskar-300x300-1-e1728462710452.webp' },
  { name: 'Alok Singh', title: 'JRF JNU', text: "Launch Pad English Learning Institute has completely changed the way I look at language learning. The expert guidance, interactive sessions, and focus on practical skills have made learning English not only effective but also enjoyable. A big thank you to the dedicated team at Launch Pad!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2022/01/Alok-Singh-JRF-JNU-e1728462868609-1024x1024.jpg' },
  { name: 'Goorav Soodh', title: 'Tourist Guide', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Gorav-Soodh-tourist-Guide.webp' },
  { name: 'Taran Veer kaur', title: 'Nursing Staff (AIIMS)', text: "Thank you, Launch Pad English, for your amazing support and guidance! As a Nursing Officer, I was initially apprehensive about my English skills, but the dedicated instructors at Launch Pad made all the difference. The curriculum was comprehensive, covering all necessary topics for my competitive exams. I truly appreciate the personalized attention I received, which helped me grasp complex concepts easily. I'm now confident and ready to tackle my exams, thanks to the wonderful team at Launch Pad English!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/05/file-2-1-1-e1728370699889.jpg' },
  { name: 'Sona Sinha', title: 'Doctor', text: "I am truly thankful to Launch Pad English for the incredible support I received during my preparation for competitive exams. The curriculum was tailored to meet my needs, focusing on practical applications and exam strategies. The friendly and encouraging environment made learning enjoyable. Thanks to the dedicated faculty, I feel equipped and confident. Highly recommend Launch Pad English to anyone looking to enhance their English skills!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Sona-Sinha-Doctor.webp' },
  { name: 'Ashutosh', title: 'Lawyer', text: "Thank you, Launch Pad English, for the amazing experience in your English for Competitive Exams program! As a lawyer, I needed a solid foundation in English, and your comprehensive course exceeded my expectations. The practical exercises and mock tests were particularly beneficial in honing my skills. I appreciate the hard work and commitment of the instructors. I couldn't have done it without you!", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/a9a491c0-97b0-41e9-b976-f9817ab0c391-209x300-1-e1728986901720.webp' },
  { name: 'Ram Vinay Gupta', title: 'Teacher', text: "Enrolling in the Spoken English course at Launch Pad English has been one of the best decisions of my career. The faculty is exceptional, providing personalized attention and valuable feedback. I am grateful for the skills I have gained, which have enriched my teaching approach and improved my interactions with students.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/6f840618-3433-4917-baac-7805e3af3ec2-300x300-1.webp' },
  { name: 'Vibha Singh', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/vibha-shingh-launch-pad-english-review.webp' },
  { name: 'Subhrat', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/subrat-launch-pad-english-review.webp' },
  { name: 'Simran Rai', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Simran-Rai.webp' },
  { name: 'Saksham Pratap', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Saksham-pratap-singh-launch-pad-english-review.webp' },
  { name: 'Rshin Aribam', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/rshin-aribam-launch-pad-english-review.webp' },
  { name: 'Riyaz Adhikari', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/riyaz-adhikari-launch-pad-english-review.webp' },
  { name: 'Rahul Singh', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Rahul-Singh-Launch-Pad-Englsih-review.webp' },
  { name: 'Pratham Aggarwal', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Pratham-Aggarwal-launch-Pad-English-review.webp' },
  { name: 'Pallavi Singh', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Pallavi-Singh.webp' },
  { name: 'Namita Pradhan', title: 'MCA', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Namita-Pradhan-launch-pad-english-review.webp' },
  { name: 'Moni', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Moni-launch-pad-english-review.webp' },
  { name: 'Geeta', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Geeta-launch-pad-english-review.webp' },
  { name: 'Anjali', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Anjali-Student-of-Launch-Pad-English-review.webp' },
  { name: 'Dev', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Dev-launch-pad-english-review.webp' },
  { name: 'Anubhav Rodhia', title: 'Student', text: '', photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Anubhav-rodhia-launch-pad-english-review.webp' },
  { name: 'Avinashi Lal', title: 'Student', text: "The dedication and expertise of the instructors at Launch Pad English Learning Institute are truly remarkable. The personalized attention, systematic approach, and abundant resources have made my English learning journey both smooth and fulfilling. An institute I would recommend to anyone seeking to enhance their language skills.", photo: 'https://www.launchpadenglish.com/wp-content/uploads/2024/10/Avinashi-Lal-LAunch-Pad-English-review.webp' },
];

async function importTestimonials() {
  await connectDB();

  console.log(`Importing ${TESTIMONIALS.length} testimonials...`);
  let created = 0;
  let skipped = 0;
  for (const t of TESTIMONIALS) {
    const exists = await Review.findOne({ name: t.name, courseSlug: 'general', source: 'admin' });
    if (exists) {
      skipped++;
      continue;
    }
    await Review.create({
      source: 'admin',
      courseSlug: 'general',
      name: t.name,
      role: t.title || '',
      stars: 5,
      text: t.text || '',
      photoUrl: t.photo || '',
      approved: true,
      featured: false,
    });
    created++;
  }

  console.log(`Done. Created ${created}, skipped ${skipped} (already present).`);
  await mongoose.disconnect();
  process.exit(0);
}

module.exports = { TESTIMONIALS };

if (require.main === module) {
  importTestimonials().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
