// Source content for the 5 courses, adapted from the uploaded course pages
// (basic-spoken-english.html, advanced-spoken-english.html,
// complete-basic-advanced-spoken-english.html, ielts-preparation-course.html,
// pte-preparation-course.html). This is loaded once by seed.js into MongoDB.
// After seeding, all edits (especially pricing.online/offline mrp & offer)
// should be made via the DB / admin API, not this file.

const BATCH_TIMINGS = {
  online: [
    '9:00 AM - 11:00 AM',
    '11:00 AM - 1:00 PM',
    '1:00 PM - 3:00 PM',
    '9:00 PM - 10:30 PM',
  ],
  offline: [
    '3:00 PM - 5:00 PM',
    '4:00 PM - 6:00 PM',
    '5:00 PM - 7:00 PM',
    '6:00 PM - 8:00 PM',
    '7:00 PM - 9:00 PM',
  ],
};

const courses = [
  {
    slug: 'basic-spoken-english',
    title: 'Basic Spoken English Course',
    tagline: '3-Month Professional Spoken English Program for Beginners',
    duration: '3 Months (12 Weeks)',
    level: 'Beginner',
    overview:
      'This comprehensive 12-week course is designed for beginners who want to speak English confidently in daily life, academics, interviews, and the workplace. The program combines grammar, vocabulary, pronunciation, speaking practice, role plays, group discussions, and personality development, delivered by experienced trainers in small, focused batches.',
    highlights: [
      'Duration: 3 Months (12 Weeks)',
      'Mode: Online & Offline',
      'Study Material Included',
      'Course Completion Certificate',
      'Weekly Assessments & Speaking Practice',
      'Experienced Trainers',
    ],
    whoShouldJoin: [
      'Absolute beginners with little to no spoken English exposure',
      'School & college students',
      'Job seekers preparing for interviews',
      'Working professionals wanting workplace-ready English',
    ],
    syllabus: [
      { module: 'Module 1 - Introduction (Week 1)', points: ['English Alphabet & Pronunciation', 'Greetings & Introductions', 'Self Introduction', 'Classroom English', '100 Common Vocabulary Words'] },
      { module: 'Module 2 - Basic Grammar (Weeks 2-3)', points: ['Parts of Speech', 'Pronouns', 'Articles', 'Nouns', 'Adjectives', 'Prepositions', 'This/That/These/Those', 'There is / There are'] },
      { module: 'Module 3 - Tenses (Weeks 4-6)', points: ['Present Simple', 'Present Continuous', 'Past Simple', 'Future Simple', 'Daily Routine', 'Question Formation', 'Negative Sentences'] },
      { module: 'Module 4 - Speaking Functions (Weeks 7-8)', points: ['Asking & Answering Questions', 'Making Requests', 'Giving Directions', 'Likes & Dislikes', 'Talking about Hobbies', 'Describing People, Places & Things', 'Telephone Conversation'] },
      { module: 'Module 5 - Everyday Communication (Weeks 9-10)', points: ['Shopping', 'Restaurant', 'Railway Station', 'Airport', 'Bank', 'Hospital', 'Job Interview Basics'] },
      { module: 'Module 6 - Confidence Building (Weeks 11-12)', points: ['Picture Description', 'Storytelling', 'Role Plays', 'Group Discussion', 'Public Speaking', 'Common Mistakes', 'Revision & Final Assessment'] },
    ],
    dailyPattern: [
      'Vocabulary - 10 Minutes',
      'Grammar - 20 Minutes',
      'Speaking Practice - 20 Minutes',
      'Role Play - 20 Minutes',
      'Pronunciation & Doubts - 10 Minutes',
    ],
    outcomes: [
      'Introduce yourself confidently',
      'Speak confidently in everyday situations',
      'Improve pronunciation and fluency',
      'Use basic grammar and tenses correctly',
      'Participate in interviews and group discussions',
      'Develop confidence in public speaking',
    ],
    batchTimings: BATCH_TIMINGS,
    faqs: [
      { q: 'Is this course suitable for beginners?', a: 'Yes, it is designed from the ground up for absolute beginners.' },
      { q: 'Will I receive a certificate?', a: 'Yes, a course completion certificate is provided.' },
      { q: 'Is study material included?', a: 'Yes, complete study material is included in the fee.' },
      { q: 'Are live classes conducted?', a: 'Yes, both online and offline batches have live, trainer-led classes.' },
      { q: 'Can working professionals join?', a: 'Yes, we run flexible morning, afternoon and evening batches.' },
    ],
    images: [],
    thumbnail: '',
    pricing: { online: { mrp: 17999, offer: 14999 }, offline: { mrp: 19999, offer: 17999 } },
    displayOrder: 1,
    active: true,
  },
  {
    slug: 'advanced-spoken-english',
    title: 'Advanced Spoken English Course',
    tagline: '3-Month Advanced Communication & Professional English Program',
    duration: '3 Months (12 Weeks)',
    level: 'Advanced',
    overview:
      'Designed for learners who already have a basic understanding of English and want to achieve fluency, confidence, and professional, workplace-ready communication. The course focuses on real-life communication, presentations, interviews, pronunciation, personality development, and advanced vocabulary.',
    highlights: [
      'Duration: 3 Months (12 Weeks)',
      'Mode: Online & Offline',
      'Study Material Included',
      'Certificate Included',
      'Live Speaking Practice',
      'Mock Interviews & Presentations',
    ],
    whoShouldJoin: [
      'Learners with basic English who want fluency and confidence',
      'Professionals preparing for interviews, meetings & presentations',
      'Anyone wanting advanced grammar, idioms and business English',
    ],
    syllabus: [
      { module: 'Module 1 (Week 1): Advanced Communication Skills', points: ['Advanced self-introduction', 'Small talk & networking', 'Conversation starters & closers', 'Formal vs informal English', 'Confidence building'] },
      { module: 'Module 2 (Weeks 2-3): Advanced Grammar for Speaking', points: ['Revision of all tenses', 'Modal verbs', 'Conditionals', 'Passive voice', 'Reported speech', 'Relative clauses', 'Question tags', 'Inversion', 'Common grammar mistakes'] },
      { module: 'Module 3 (Weeks 4-5): Vocabulary & Idiomatic English', points: ['100+ phrasal verbs', 'Idioms & expressions', 'Collocations', 'Synonyms & antonyms', 'Academic & business vocabulary', 'Powerful everyday expressions'] },
      { module: 'Module 4 (Week 6): Pronunciation & Accent Improvement', points: ['Word stress', 'Sentence stress', 'Intonation', 'Connected speech', 'Silent letters', 'Common pronunciation errors'] },
      { module: 'Module 5 (Weeks 7-8): Real-Life Speaking Situations', points: ['Job interviews', 'Group discussions', 'Meetings', 'Presentations', 'Negotiation', 'Public speaking', 'Debate', 'Telephone & video-call communication', 'Customer service conversations'] },
      { module: 'Module 6 (Week 9): Personality Development & Soft Skills', points: ['Body language', 'Stage presence', 'Leadership communication', 'Active listening', 'Persuasion', 'Emotional intelligence'] },
      { module: 'Module 7 (Week 10): Professional English', points: ['Email communication', 'Office conversations', 'Business meetings', 'Resume & interview practice', 'Networking'] },
      { module: 'Module 8 (Weeks 11-12): Fluency Development', points: ['Extempore speaking', 'Storytelling', 'Picture description', 'Opinion sharing', 'News discussion', 'Book/Movie reviews', 'Mock interviews', 'Final presentations', 'Personalized feedback'] },
    ],
    dailyPattern: [
      'Warm-up Conversation - 10 min',
      'Vocabulary & Pronunciation - 15 min',
      'Grammar in Context - 15 min',
      'Speaking Activities / Debate / Role Play - 35 min',
      'Feedback & Error Correction - 15 min',
    ],
    outcomes: [
      'Speak fluently and confidently',
      'Participate in debates and discussions',
      'Deliver professional presentations',
      'Handle job interviews successfully',
      'Use advanced grammar naturally',
      'Use idioms, collocations and phrasal verbs correctly',
      'Improve pronunciation and accent',
      'Communicate effectively in workplaces',
    ],
    batchTimings: BATCH_TIMINGS,
    faqs: [
      { q: 'Who is this course for?', a: 'College students and working professionals who already know basic English and want fluency.' },
      { q: 'Is a certificate provided?', a: 'Yes, on successful completion of the program.' },
      { q: 'Is study material included?', a: 'Yes, complete material is included.' },
      { q: 'Are batches flexible?', a: 'Yes, we offer flexible online and offline batch timings.' },
      { q: 'Do I get personal feedback?', a: 'Yes, live interaction and personalized feedback throughout.' },
    ],
    images: [],
    thumbnail: '',
    pricing: { online: { mrp: 17999, offer: 14999 }, offline: { mrp: 19999, offer: 17999 } },
    displayOrder: 2,
    active: true,
  },
  {
    slug: 'complete-basic-advanced-spoken-english',
    title: 'Complete Spoken English Program (Basic + Advanced)',
    tagline: 'An intensive up to 6-month program from beginner level to advanced fluency',
    duration: 'Up to 6 Months',
    level: 'Beginner to Advanced',
    overview:
      'Our flagship program combines the entire Basic and Advanced curriculum into one structured learning journey. Students receive practical communication training, regular speaking practice, grammar support, personality development, interview coaching, business communication, pronunciation improvement, public speaking sessions, and continuous trainer feedback to ensure confident English communication in academic, professional, and social environments.',
    highlights: [
      'Beginner to Advanced Curriculum',
      'Up to 6 Months Duration',
      'Offline & Online Batches',
      'Study Material Included',
      'Course Completion Certificate',
      'Weekly Assessments',
      'Mock Interviews',
      'Group Discussions',
      'Personality Development',
      'Public Speaking',
    ],
    whoShouldJoin: [
      'School & College Students',
      'Working Professionals',
      'Job Seekers',
      'Competitive Exam Aspirants',
      'Business Owners',
      'Anyone wanting fluent English from scratch to advanced level',
    ],
    syllabus: [
      { module: 'Phase 1 - Basic Spoken English', points: ['English alphabet & pronunciation', 'Grammar & vocabulary foundations', 'Tenses & sentence formation', 'Daily conversation & role plays', 'Shopping / restaurant English', 'Confidence building, storytelling & public speaking'] },
      { module: 'Phase 2 - Intermediate English', points: ['Advanced sentence formation', 'Vocabulary expansion', 'Pronunciation improvement', 'Descriptive speaking', 'Group discussions & communication activities', 'Interview preparation & presentation skills'] },
      { module: 'Phase 3 - Advanced Spoken English', points: ['Business English & idioms', 'Phrasal verbs, meetings, negotiations', 'Leadership communication', 'Public speaking & debate', 'Workplace English & personality development', 'Mock interviews & real-life communication'] },
    ],
    dailyPattern: [
      'Vocabulary Building',
      'Grammar in Context',
      'Pronunciation Practice',
      'Speaking Activities',
      'Role Plays & Group Discussion',
      'Error Correction & Doubt Solving',
    ],
    outcomes: [
      'Speak fluent English confidently',
      'Improve pronunciation and vocabulary',
      'Handle interviews and presentations',
      'Master professional communication',
      'Participate in debates and discussions',
      'Communicate naturally in daily life',
    ],
    batchTimings: BATCH_TIMINGS,
    faqs: [
      { q: 'Does this cover both Basic and Advanced levels?', a: 'Yes, it is the complete beginner-to-advanced journey in one program.' },
      { q: 'How long does it take?', a: 'Up to 6 months, depending on your starting level and batch pace.' },
      { q: 'Is mentor support included?', a: 'Yes, along with weekly tests and continuous feedback.' },
      { q: 'Is it available offline too?', a: 'Yes, both online live classes and offline classroom training are available.' },
    ],
    images: [],
    thumbnail: '',
    pricing: { online: { mrp: 28999, offer: 19999 }, offline: { mrp: 28999, offer: 19999 } },
    displayOrder: 3,
    active: true,
  },
  {
    slug: 'ielts-preparation-course',
    title: 'IELTS Preparation Course',
    tagline: 'Professional 12-week IELTS coaching to help you achieve Band 7-9',
    duration: '12 Weeks',
    level: 'Exam Preparation',
    overview:
      'A professional 12-week IELTS coaching program designed to help students achieve Band 7-9 through expert guidance, structured practice, weekly mock tests, and personalized feedback across all four skills: Listening, Reading, Writing and Speaking.',
    highlights: [
      '12 Weeks Intensive Training',
      'Listening, Reading, Writing & Speaking',
      'Band 7-9 Preparation',
      'Latest Cambridge IELTS Materials',
      'Weekly Mock Tests',
      'Study Material & Certificate Included',
    ],
    whoShouldJoin: [
      'Students applying to study abroad',
      'Professionals applying for migration or jobs overseas',
      'Anyone targeting a high IELTS band score',
    ],
    syllabus: [
      { module: 'Week 1 - Foundation & Diagnostic Test', points: ['IELTS format & scoring system', 'Diagnostic test', 'Grammar revision', 'Sentence structure & academic vocabulary'] },
      { module: 'Week 2 - Grammar & Vocabulary', points: ['Active/passive voice', 'Reported speech', 'Modal verbs & conditionals', 'Connectors, collocations & synonyms'] },
      { module: 'Week 3 - Speaking Skills', points: ['Part 1 Interview', 'Part 2 Cue Card', 'Part 3 Discussion', 'Pronunciation, fluency & intonation'] },
      { module: 'Week 4 - Writing Task 1', points: ['Graphs, tables, maps, process charts', 'Paragraph organization', 'Grammar accuracy'] },
      { module: 'Week 5 - Writing Task 2', points: ['Opinion essays', 'Discussion essays', 'Advantages/disadvantages', 'Problem-solution & double-question essays'] },
      { module: 'Week 6 - Reading Skills', points: ['Matching headings', 'True/False/Not Given', 'Sentence & summary completion', 'Speed-reading strategies'] },
      { module: 'Week 7 - Listening Skills', points: ['Sections 1-4 practice', 'Note & map completion', 'Multiple choice & sentence completion'] },
      { module: 'Week 8 - Advanced Practice', points: ['Vocabulary booster', 'Writing evaluation & error analysis', 'Daily speaking practice', 'High-band strategies'] },
      { module: 'Week 9 - Full Mock Test', points: ['Complete IELTS mock test', 'Personalized improvement plan'] },
      { module: 'Week 10 - Intensive Practice', points: ['Weak-area improvement', 'Speaking interviews & writing corrections', 'Reading speed & listening accuracy'] },
      { module: 'Week 11 - Mock Test 2', points: ['Band prediction', 'Score analysis', 'One-to-one counselling'] },
      { module: 'Week 12 - Final Revision', points: ['Exam-day strategies', 'Confidence building', 'Common mistakes', 'Final mock examination'] },
    ],
    dailyPattern: [
      'Grammar - 20 Minutes',
      'Vocabulary - 15 Minutes',
      'Speaking - 30 Minutes',
      'Reading / Listening - 30 Minutes',
      'Writing - 20 Minutes',
      'Homework Discussion - 5 Minutes',
    ],
    outcomes: [
      'Develop all four IELTS skills',
      'Improve grammar & academic vocabulary',
      'Master IELTS strategies and time management',
      'Build confidence through speaking practice',
      'Achieve target band score through mock-test feedback',
    ],
    batchTimings: { online: BATCH_TIMINGS.online, offline: BATCH_TIMINGS.offline },
    faqs: [
      { q: 'What band score can I expect?', a: 'The program is structured to help learners reach Band 7-9, depending on starting level and practice.' },
      { q: 'Which materials are used?', a: 'Latest Cambridge IELTS books, grammar notes, vocabulary lists and mock test booklets.' },
      { q: 'How many mock tests are included?', a: 'Weekly mock activities plus two full-length mock exams (Weeks 9 & 11).' },
      { q: 'Is coaching available offline?', a: 'Yes, classroom coaching with a dedicated speaking lab is available.' },
    ],
    images: [],
    thumbnail: '',
    pricing: { online: { mrp: 24999, offer: 19999 }, offline: { mrp: 24999, offer: 19999 } },
    displayOrder: 4,
    active: true,
  },
  {
    slug: 'pte-preparation-course',
    title: 'PTE Academic Preparation Course',
    tagline: 'A comprehensive 12-week Pearson Test of English preparation program',
    duration: '12 Weeks',
    level: 'Exam Preparation',
    overview:
      'A comprehensive 12-week PTE Academic preparation program focused on communication, AI-scored task mastery, time management, and exam confidence - designed for scores of 65 to 90+.',
    highlights: [
      'Complete coverage of all PTE Academic modules',
      'AI-style practice and scoring techniques',
      'Personalized trainer feedback',
      'Weekly mock tests',
      'Study Material & Certificate Included',
      'Designed for scores of 65-90+',
    ],
    whoShouldJoin: [
      'Students planning to study abroad',
      'Professionals applying for migration',
      'Candidates switching from IELTS to PTE',
      'Anyone targeting a high PTE score',
    ],
    syllabus: [
      { module: 'Week 1', points: ['Introduction to PTE Academic', 'Scoring system & diagnostic test', 'Grammar revision & vocabulary foundation'] },
      { module: 'Week 2', points: ['Grammar refinement & sentence structure', 'Collocations & academic vocabulary', 'Writing basics'] },
      { module: 'Week 3 - Speaking Tasks', points: ['Read Aloud', 'Repeat Sentence', 'Describe Image', 'Re-tell Lecture', 'Answer Short Question'] },
      { module: 'Week 4 - Writing', points: ['Summarize Written Text', 'Essay Writing', 'Coherence, templates & grammar accuracy'] },
      { module: 'Week 5 - Reading', points: ['Fill in the Blanks', 'Re-order Paragraphs', 'Multiple Choice', 'Speed reading strategies'] },
      { module: 'Week 6 - Listening', points: ['Summarize Spoken Text', 'Highlight Correct Summary', 'Select Missing Word', 'Dictation'] },
      { module: 'Week 7', points: ['Pronunciation & oral fluency', 'Intonation & accent improvement', 'Speaking confidence'] },
      { module: 'Week 8', points: ['Advanced strategies & time management', 'Error correction', 'Vocabulary booster'] },
      { module: 'Week 9', points: ['Full-length mock test', 'Score analysis & personal feedback'] },
      { module: 'Week 10', points: ['Weak-area improvement', 'Intensive practice sessions'] },
      { module: 'Week 11', points: ['Advanced mock test', 'Score prediction', 'One-to-one mentoring'] },
      { module: 'Week 12', points: ['Final revision & exam strategy', 'Confidence building', 'Complete mock examination'] },
    ],
    dailyPattern: [
      'Grammar - 20 Minutes',
      'Vocabulary - 15 Minutes',
      'Speaking - 30 Minutes',
      'Reading / Listening - 30 Minutes',
      'Writing - 20 Minutes',
      'Homework Discussion - 5 Minutes',
    ],
    outcomes: [
      'Develop Listening, Reading, Speaking & Writing skills',
      'Master all PTE question types',
      'Improve pronunciation and oral fluency',
      'Increase vocabulary and grammar accuracy',
      'Build confidence through regular assessments',
    ],
    batchTimings: BATCH_TIMINGS,
    faqs: [
      { q: 'What score can I target?', a: 'The program is designed for scores ranging from 65 to 90+, depending on starting level.' },
      { q: 'Is AI-style scoring practice included?', a: 'Yes, tasks are practiced using AI-scoring-aligned techniques and strategies.' },
      { q: 'What materials do I get?', a: 'Official PTE practice material, grammar notes, vocabulary lists and mock test booklets.' },
      { q: 'Is offline coaching available?', a: 'Yes, classroom coaching with a dedicated speaking lab and trainer feedback.' },
    ],
    images: [],
    thumbnail: '',
    pricing: { online: { mrp: 24999, offer: 17999 }, offline: { mrp: 24999, offer: 17999 } },
    displayOrder: 5,
    active: true,
  },
];

module.exports = courses;
